name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python "3.10"
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint anybadge
    - name: Analysing the code with pylint & Create badge
      run: |
        coverage=$(pylint -rn -fparseable backend/src | grep "Your code has been rated at" | awk '{print $7}' | awk -F '/' '{print $1}')
        anybadge --value=$coverage --file badges/coverage.svg -l pylint 2=red 4=orange 8=yellow 10=green
    - name: Commit badge
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add badges/coverage.svg
        git commit -m "Add coverage badge"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}